import { useEffect, useMemo, useState } from "react";

export default function Reports() {
  const [data, setData] = useState([]);
  const [ratePerKwh] = useState(12);
  const [systemCost] = useState(1500000);
  const [co2Factor] = useState(0.7);

  useEffect(() => {
    const raw = localStorage.getItem("energyData");
    if (raw) {
      try {
        setData(JSON.parse(raw));
      } catch {
        setData([]);
      }
    }
  }, []);

  const cleaned = useMemo(() => {
    return data
      .map((r) => ({
        date: r.date || r.Date || r.month || r.Month || "",
        kwh: Number(
          r.kwh ||
            r.KWH ||
            r.consumption ||
            r.Consumption ||
            r.usage ||
            r.Usage ||
            0
        ),
      }))
      .filter((r) => r.date && Number.isFinite(r.kwh) && r.kwh > 0);
  }, [data]);

  const annualKwh = useMemo(() => {
    if (!cleaned.length) return 0;
    const last12 = cleaned.slice(-12);
    const sum = last12.reduce((s, x) => s + x.kwh, 0);
    return cleaned.length < 12 ? (sum / cleaned.length) * 12 : sum;
  }, [cleaned]);

  const summary = useMemo(() => {
    if (!cleaned.length) return null;

    const values = cleaned.map((x) => x.kwh);
    const mean = values.reduce((a, b) => a + b, 0) / values.length;
    const peak = Math.max(...values);

    return {
      dataPoints: cleaned.length,
      avgMonthly: Math.round(mean),
      peakKwh: Math.round(peak),
      annualKwh: Math.round(annualKwh),
    };
  }, [cleaned, annualKwh]);

  const scenarios = useMemo(() => {
    const coverageOptions = [0.3, 0.5, 0.7];
    return coverageOptions.map((coverage) => {
      const kwhOffset = annualKwh * coverage;
      const savingsPerYear = kwhOffset * ratePerKwh;
      const paybackYears = savingsPerYear <= 0 ? null : systemCost / savingsPerYear;

      const co2ReducedKg = kwhOffset * co2Factor;
      const co2ReducedTons = co2ReducedKg / 1000;

      return {
        coverage: Math.round(coverage * 100),
        kwhOffset: Math.round(kwhOffset),
        savingsPerYear: Math.round(savingsPerYear),
        paybackYears: paybackYears ? Number(paybackYears.toFixed(1)) : null,
        co2ReducedTons: Number(co2ReducedTons.toFixed(2)),
      };
    });
  }, [annualKwh, ratePerKwh, systemCost, co2Factor]);

  const reportObject = useMemo(() => {
    if (!summary) return null;
    return {
      generatedAt: new Date().toISOString(),
      datasetSummary: summary,
      assumptions: {
        ratePerKwhPHP: ratePerKwh,
        estimatedSystemCostPHP: systemCost,
        co2FactorKgPerKwh: co2Factor,
      },
      scenarioResults: scenarios,
      note: "This report is generated by the frontend prototype. Final version will generate official PDF via backend.",
    };
  }, [summary, ratePerKwh, systemCost, co2Factor, scenarios]);

  const downloadText = (filename, text, mime) => {
    const blob = new Blob([text], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportJSON = () => {
    if (!reportObject) return;
    downloadText(
      "renewable_dss_report.json",
      JSON.stringify(reportObject, null, 2),
      "application/json"
    );
  };

  const exportScenarioCSV = () => {
    if (!scenarios.length) return;
    const header = "scenario_percent,kwh_offset_per_year,savings_per_year_php,payback_years,co2_reduced_tons_per_year";
    const lines = scenarios.map((s) =>
      [
        s.coverage,
        s.kwhOffset,
        s.savingsPerYear,
        s.paybackYears ?? "",
        s.co2ReducedTons,
      ].join(",")
    );
    const csv = [header, ...lines].join("\n");
    downloadText("scenario_results.csv", csv, "text/csv");
  };

  return (
    <div style={{ color: "#222" }}>
      <h2 style={{ marginBottom: 8, color: "#111" }}>Reports / Export</h2>
      <p style={{ marginTop: 0, color: "#555" }}>
        Generate a report summary and export outputs for documentation and planning.
      </p>

      {!summary ? (
        <div
          style={{
            background: "#fff3cd",
            border: "1px solid #ffeeba",
            padding: 14,
            borderRadius: 12,
            color: "#664d03",
          }}
        >
          Wala pang loaded data. Please upload muna sa <b>Data Upload</b> page.
        </div>
      ) : (
        <>
          {/* Export Buttons */}
          <div
            style={{
              display: "flex",
              gap: 10,
              alignItems: "center",
              background: "white",
              padding: 14,
              borderRadius: 12,
              boxShadow: "0 2px 10px rgba(0,0,0,0.06)",
            }}
          >
            <button style={btn} onClick={exportScenarioCSV}>
              Export Scenario CSV
            </button>
            <button style={btn} onClick={exportJSON}>
              Export Report JSON
            </button>

            <div style={{ marginLeft: "auto", fontSize: 12, color: "#777" }}>
              (PDF export will be added via backend)
            </div>
          </div>

          {/* Report Preview */}
          <div style={{ marginTop: 18 }}>
            <h3 style={{ margin: "0 0 10px 0", color: "#111" }}>Report Preview</h3>

            <div
              style={{
                background: "white",
                borderRadius: 12,
                padding: 16,
                boxShadow: "0 2px 10px rgba(0,0,0,0.06)",
              }}
            >
              <SectionTitle title="1. Dataset Summary" />
              <Grid4>
                <MiniCard title="Data Points (months)" value={summary.dataPoints} />
                <MiniCard title="Avg Monthly kWh" value={summary.avgMonthly.toLocaleString()} />
                <MiniCard title="Peak kWh" value={summary.peakKwh.toLocaleString()} />
                <MiniCard title="Estimated Annual kWh" value={summary.annualKwh.toLocaleString()} />
              </Grid4>

              <SectionTitle title="2. Assumptions" />
              <ul style={{ marginTop: 0 }}>
                <li>Electricity Rate: ₱{ratePerKwh} per kWh</li>
                <li>Estimated System Cost: ₱{systemCost.toLocaleString()}</li>
                <li>CO₂ Factor: {co2Factor} kg CO₂ per kWh</li>
              </ul>

              <SectionTitle title="3. Scenario Results" />
              <div style={{ overflowX: "auto" }}>
                <table style={{ width: "100%", borderCollapse: "collapse" }}>
                  <thead>
                    <tr>
                      <th style={th}>Scenario</th>
                      <th style={th}>kWh Offset / Year</th>
                      <th style={th}>Savings / Year (PHP)</th>
                      <th style={th}>Payback (Years)</th>
                      <th style={th}>CO₂ Reduced (tons/yr)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {scenarios.map((s, i) => (
                      <tr key={i}>
                        <td style={td}><b>{s.coverage}%</b></td>
                        <td style={td}>{s.kwhOffset.toLocaleString()}</td>
                        <td style={td}>{s.savingsPerYear.toLocaleString()}</td>
                        <td style={td}>{s.paybackYears ?? "-"}</td>
                        <td style={td}>{s.co2ReducedTons.toFixed(2)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div
                style={{
                  marginTop: 14,
                  background: "#f6f7fb",
                  border: "1px solid #e3e7ee",
                  borderRadius: 12,
                  padding: 12,
                  color: "#333",
                }}
              >
                <b>Note:</b> This preview is generated by the frontend prototype. In the final system,
                reports will be generated as a formal PDF through the backend.
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function SectionTitle({ title }) {
  return (
    <div style={{ marginTop: 18, marginBottom: 8, fontWeight: 900, color: "#111" }}>
      {title}
    </div>
  );
}

function Grid4({ children }) {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
      {children}
    </div>
  );
}

function MiniCard({ title, value }) {
  return (
    <div
      style={{
        background: "#ffffff",
        border: "1px solid #eef0f4",
        borderRadius: 12,
        padding: 12,
      }}
    >
      <div style={{ fontSize: 12, color: "#666" }}>{title}</div>
      <div style={{ fontSize: 16, fontWeight: 900, color: "#111", marginTop: 6 }}>
        {value}
      </div>
    </div>
  );
}

const btn = {
  padding: "10px 12px",
  borderRadius: 10,
  border: "none",
  background: "#0b3d2e",
  color: "white",
  fontWeight: 900,
  cursor: "pointer",
};

const th = {
  textAlign: "left",
  padding: "10px 10px",
  borderBottom: "1px solid #eee",
  fontSize: 13,
  color: "#555",
};

const td = {
  padding: "10px 10px",
  borderBottom: "1px solid #f2f2f2",
};